Repository cgkineo/adapt-hotgrid, pull requests merged in 2023-05, with the labels that each got.

#123 Fix: Realign breakpoint for column layout to medium and above (fixes #122)
  js/HotgridView.js
  package.json
Labels: bug, released

#114 Fix: Jaws highlight issue for close button (fixes #113)
  templates/hotgridPopupToolbar.jsx
Labels: bug, accessibility

#121 Fix: Item popup title missing ARIA heading role (fixes #120)
  templates/hotgridPopup.jsx
Labels: bug, accessibility

#117 Fix: Add completion icon styles (fixes #99)
  less/hotgrid.less
  templates/hotgrid.jsx
Labels: enhancement, accessibility

#125 Fix: compile reactHelpers (fixes #124)
  templates/hotgridPopup.jsx
Labels: bug, accessibility
