Repository cgkineo/adapt-hotgrid, pull requests merged in 2023-02, with the labels that each got.

#97 Fix: ES6/JSX conversion and schema AAT update (fixes #92)
  README.md
  bower.json
  example.json
  js/HotgridModel.js
  js/HotgridPopupView.js
  js/HotgridView.js
  js/adapt-hotgrid.js
  js/hotgridPopupView.js
  js/hotgridView.js
  less/hotgrid.less
  package.json
  properties.schema
  schema/component.schema.json
  schema/course.schema.json
  templates/hotgrid.hbs
  templates/hotgrid.jsx
  templates/hotgridPopup.hbs
  templates/hotgridPopup.jsx
  templates/hotgridPopupToolbar.jsx
Labels: enhancement

#103 Fix: Fix popup close button aria-label (fixes #102)
  templates/hotgridPopupToolbar.jsx
Labels: accessibility

#101 Fix: Add missing inputType schema values (fixes #100)
  properties.schema
Labels: bug

#106 Fix: README.md - Remove version number, minor grammatical fix (fixes #105)
  README.md
Labels: enhancement
